### ISSUE TITLE
Embeddable rxmarbles

### ISSUE THREAD

**Issue by xgrommx** [staltz/rxmarbles#1]
Hello @staltz 

I'm working on a book http://xgrommx.github.io/rx-book. Can I use your interesting work in my book for visualization operators of RxJs.

**Comment by staltz** [comment]
Draft implementation for this:

- Make the sandbox an HTML5 custom element
- Use polyfill http://webcomponents.org/polyfills/custom-elements/
- Make an npm build script just for building the embeddable custom element

**Comment by staltz** [comment]
Done in [v1.3.1](https://github.com/staltz/rxmarbles/releases/tag/v1.3.1)
Ping @xgrommx

**Comment by xgrommx** [comment]
Awesome! Thank you @staltz. But I have one small question. How can I use my own source for rxmarbles? For example I have one stream and I want to visualize this one.

**Comment by staltz** [comment]
Can't use it yet. I would need to build it as attributes to the custom element, e.g.:

```html
<rx-marbles inputs="[(0,10),(1,20),(3,40)],[(2,15),(4,50)]" operator="merge">
```

Or something like that

**Comment by xgrommx** [comment]
Looks good =) Thanks, it will be useful.
