### ISSUE TITLE
Do not hide overlapped marbles

### ISSUE THREAD

**Issue by sirreal** [staltz/rxmarbles#14]
If you have two marbles in the same output, the "earlier" marble is completely hidden underneath the "later" marble. It appears that there is only one marble at that position, and it is unclear that there are actually multiple marbles at the same position.

I noticed this when looking at `pausableBuffered`. If you slide the `pause` `false` slider to the correct position, `pausable` and `pausableBuffered` appear to have the same behavior. This is confusing because `pausableBuffered` actually has overlapping marbles which can't be seen (until you open the source).

Here is `pausable`, where some marbles are absent from the result stream:

![pausable](https://cloud.githubusercontent.com/assets/841763/7881514/245288ba-0604-11e5-988d-7dd3ebd9a5bd.png)

Compare with `pausableBuffered`, where marbles are present in the result stream (`5`, `6`, `7`) but appear to be absent due to overlap:

![pausablebuffered](https://cloud.githubusercontent.com/assets/841763/7881529/464759f0-0604-11e5-88e1-a849e43683db.png)

**Comment by staltz** [comment]
Yes, this is one of the next things to do https://github.com/staltz/rxmarbles/blob/master/TODO#L75
Currently working on animation, which is ~75% done.
