### ISSUE TITLE
Diagrams don't show stream completion

### ISSUE THREAD

**Issue by marcuswhit** [staltz/rxmarbles#2]
To be correct, both the source and result streams should indicate when they complete, if relevant.  Taking [Average] (http://rxmarbles.com/#average) as an example, the source stream appears to continue beyond when the result is produced, and it doesn't illustrate the critical detail that a result won't be produced until the source stream completes.  The result streams should also indicate when they complete.

Great site though otherwise!

**Comment by staltz** [comment]
Fixed some long time ago
