### ISSUE TITLE
Add some description for each operator

### ISSUE THREAD

**Issue by mauriciosoares** [staltz/rxmarbles#23]
Hey! RxMarbles is great! I'm learning a lot with it... But for beginners (like me) it's hard to deduce what each operator does... I have to look at the diagram, play a little bit, and than I start to understand what each of them really does...

It's just an opinion, but what you think of adding a simple and easy to understand description to each operator? Like in the `Scan` operator:

Scan
Does some crazy stuff with `x` and `y`, where `x` is the current value and `y` is the previous value.
`[PLAYABLE DIAGRAM]`

I know it's a dumb example, but I think you got the idea :)

**Comment by staltz** [comment]
I don't want to replicate what we are doing at ReactiveX.io, check out this http://reactivex.io/documentation/operators/scan.html

The plan is to build RxMarbles to such a state that it will be embedded in the docs page in ReactiveX.io, and the latter is the official guide on the operator. RxMarbles would then be just a cheatsheet for quick checks.

**Comment by xgrommx** [comment]
@mauriciosoares I am using RxMarbles with my RxBook. You can look on this page http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/map.html

**Comment by mauriciosoares** [comment]
@staltz, that makes sense...

@xgrommx, thanks for the link! It's what I wanted, a simple description with some code samples... I'll totally take a look at it.

Thanks guys.
