### ISSUE TITLE
Rights for screenshots

### ISSUE THREAD

**Issue by la-yumba** [staltz/rxmarbles#41]
Hi André,

I am the author of [Functional Programming in C#](https://www.manning.com/books/functional-programming-in-c-sharp?a_aid=functional-programming-in-c-sharp&a_bid=ad9af506) and I'd like to request permission to include a few screenshots of [rxmarbles.com](https://rxmarbles.com) in the chapter on RX, to explain some of the operators. 

Credit will be given by including the link to the site and your name in a footnote accompanying the first marble diagram that appears. I hope you're ok with this; let me know either way. 

Kind regards,
EB

**Comment by staltz** [comment]
Sure, I'm ok with it.

**Comment by la-yumba** [comment]
Excellent, Thank you!
