### ISSUE TITLE
Rewrite to RxJS 5

### ISSUE THREAD

**Issue by alanthai** [staltz/rxmarbles#42]
Would love for the project to be in RxJS 5 so that new operators can be added. Here's my attempt at rewriting it in the latest CycleJS and RxJS: https://github.com/alanthai/rxjs-marbles

**Comment by jonirrings** [comment]
nice work~~

**Comment by staltz** [comment]
Hey, this looks great. I would merge if it would be a PR. I'll also thank you by mentioning your name for the contribution :)

**Comment by bitjson** [comment]
Added @alanthai here: https://github.com/staltz/rxmarbles/pull/46/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R6
