### ISSUE TITLE
https: certificate problem

### ISSUE THREAD

**Issue by mindrones** [staltz/rxmarbles#52]
Hi, https://rxmarbles.com/ seems to have certificate problems:

![screen shot 2018-03-17 at 19 25 41](https://user-images.githubusercontent.com/1309648/37558756-2e5f705c-2a19-11e8-80f7-7702d6b1a319.png)

Thanks!

**Comment by abraham** [comment]
This should be as simple as update the DNS to use CNAME/ALIAS instead of A records.

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by staltz** [comment]
Done, will need to wait a few hours to activate the certificate

**Comment by mindrones** [comment]
Seems gone 👍

**Comment by abraham** [comment]
Enforcing https too would be great.

**Comment by staltz** [comment]
Done
