### ISSUE TITLE
RxJS 6 support

### ISSUE THREAD

**Issue by keithernet** [staltz/rxmarbles#60]
The syntax for RxJS 6 has changed pretty dramatically. Is there interest in updating the code base and examples? 

I'd be happy to work on a pull request if so.

**Comment by staltz** [comment]
Hey, thanks for volunteering, but this project is mostly useful for its visualizations of concepts, not necessarily the JS syntax, this project should also be useful to visualize general Rx concepts for other languages (e.g. RxJava, etc).
